import { error } from '@sveltejs/kit';

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
    if (params.slug === 'madrid') {
        return {
            title: 'Agencia de SEO en Madrid - Posicionamiento Orgánico',
            content: 'Welcome to our blog. Lorem ipsum dolor sit amet...',
            h1: 'Agencia SEO en Madrid',
            textoHeader:'¿Cansado de no aparecer en los primeros resultados de Google? Nuestra agencia SEO en Madrid te ayuda a mejorar la visibilidad de tu marca online. Te informamos sin compromiso.',
            serviciosHeading:'Descubre cómo podemos ayudarte con nuestros servicios especializados en SEO',
            serviciosText:'Somos una agencia SEO en Madrid, con amplia experiencia en el sector. Ayudamos a nuestros clientes mejorando la visibilidad de sus negocios en Google y aumentar el tráfico hacia su web.',
            auditoria:'Nuestros expertos en SEO analizarán todos los aspectos técnicos, de contenido y autoridad de tu web y te entregarán un informe detallado con recomendaciones prácticas. No esperes más y pide tu auditoría SEO hoy mismo.',
            consultoria:'Analizamos todas las categorías del SEO (On Page, Off Page, técnico y de contenidos) y te ofrecemos un plan personalizado para optimizar tu web. No esperes más y solicita tu presupuesto sin compromiso.',
            local:'¿Quieres mejorar tu posicionamiento local y atraer más clientes a tu negocio? En nuestra agencia SEO te ofrecemos los mejores servicios de SEO Local para que tu web destaque en Google.',
            acompañamiento: '¿Necesitas rediseñar tu web y no sabes cómo hacerlo sin perder tu posicionamiento SEO? En nuestra agencia SEO en Madrid te ayudamos a definir las nuevas URLs de tu web con un estudio previo de palabras clave y una arquitectura optimizada.',
            migracion:'En nuestra agencia SEO te ofrecemos el mejor servicio de cambio de arquitectura y redirecciones para que no pierdas tu ranking en Google. Solicita tu presupuesto sin compromiso y descubre cómo podemos ayudarte.',
            contenidos:'En nuestra agencia SEO en Madrid te ofrecemos un servicio integral de redacción, optimización y difusión de contenidos adaptados a tu público objetivo y a las exigencias de los motores de búsqueda.',
            ventajasHeading: 'Descubre las ventajas de contar con una agencia SEO en Madrid',
            ventajasText:'Te ayudamos a comprender los conceptos básicos del SEO aplicándolos en tu proyecto mediante acciones personalizadas según tu marca, sector y un estudio de la competencia en las SERPs.',
            objetivos:'Nos proponemos objetivos claros y medibles para mejorar el posicionamiento de tu web en los buscadores. Hacemos que tu negocio crezca y consiga más clientes y ventas gracias a una estrategia SEO eficaz. Si quieres saber cómo podemos ayudarte, solicita una auditoría SEO gratuita y sin compromiso.',
            metodologias:'Nuestra metodología se adapta a las necesidades de cada cliente. Realizamos un estudio y análisis previo de tu sector, competencia y público objetivo para diseñar una estrategia SEO personalizada y eficaz. ¿Quieres saber más? Contacta con nosotros y te informaremos sin compromiso.',
            seguimiento:'No solo diseñamos y ejecutamos estrategias personalizadas para cada cliente, sino que también hacemos un seguimiento constante del proyecto para medir los resultados y optimizar el rendimiento. Si quieres saber más sobre cómo trabajamos y qué beneficios podemos aportarte, solicita una auditoría gratuita de tu web ahora mismo.',
            nosotrosHeading:'Equipo de expertos en posicionamiento web en Madrid',
            nosotrosText:'Descubre cómo nuestro equipo de profesionales SEO puede ayudarte a mejorar tu posicionamiento web, aumentar tu tráfico y generar más ventas.',
            preguntasText:'¿Tienes dudas sobre el SEO y cómo puede ayudarte a mejorar tu negocio? En nuestra web encontrarás las respuestas que necesitas.',
            preguntas: [
                {
                  pregunta: "Aumenta el tráfico orgánico y atrae más clientes potenciales",
                  respuesta: ["Somos conscientes de lo importante que es el SEO para el éxito de cualquier negocio en línea, por eso estamos aquí para ayudarte a aprovechar al máximo tu presencia online. Nuestro equipo de profesionales hace uso de técnicas SEO de vanguardia, siendo conocedor de las últimas actualizaciones del algoritmo de Google. Por ello nuestros clientes estén siempre un paso por delante de la competencia.","Ofrecemos una amplia gama de servicios SEO, desde la investigación avanzada de palabras clave (keyword research), generación de contenidos de alta calidad y la optimización de la experiencia del usuario.","Si necesitas mejorar el posicionamiento web de tu sitio web en los resultados de búsqueda y atraer más tráfico orgánico, ¡no dudes en contactar con nosotros! Estaremos encantados de ayudarte a alcanzar el éxito online para tu negocio.","El posicionamiento orgánico en buscadores, también conocido como SEO (Search Engine Optimization), te ayuda a mejorar la visibilidad de tu negocio y mejorar las ventas online.","El SEO consiste en la optimización de tu web para que sea fácilmente rastreable por los motores de búsqueda como Google. El objetivo principal del SEO es mejorar la calidad y cantidad del tráfico de un sitio web a través del posicionamiento en las SERPs (resultados orgánicos de búsqueda).","Cuando un usuario realiza una búsqueda, Google hace uso de algoritmos para determinar qué URLs son más relevantes para esa búsqueda en particular. Estos algoritmos toman en cuenta diversos factores, como la relevancia del contenido, la calidad de la página, la experiencia del usuario y la autoridad de tu marca.","Para mejorar el posicionamiento de tu negocio en los resultados de búsqueda, es importante asegurarse de que su contenido es relevante y útil para los usuarios. También es importante tener en cuenta la experiencia del usuario y asegurarse de que tu sitio tenga una navegación sencilla y rápido para cargar. Además, es fundamental utilizar palabras clave relevantes y estructurar su contenido y etiquetas de manera adecuada.","El SEO puede ser una tarea desafiante, pero los resultados que te ofrece son esenciales para aumentar las conversiones de tu negocio. Un sitio web bien posicionado en los resultados de búsqueda puede atraer a más tráfico orgánico y, en última instancia, más clientes y ventas.",],
                },
                {
                  pregunta: "¿Sabes cómo funciona el SEO y cómo puede mejorar tus ventas?",
                  respuesta:["Nuestra agencia SEO en Madrid te ayuda a comprender los conceptos básicos del SEO y los aplica en tu proyecto mediante acciones personalizadas según tu marca, sector y un estudio de la competencia en las SERPs. Con nuestra ayuda, comprenderás como el SEO puede mejorar su posicionamiento en los motores de búsqueda.", "Existen muchos factores que pueden afectar el posicionamiento de un sitio web en los resultados de búsqueda, como la relevancia del contenido, la calidad del sitio, la usabilidad y la experiencia del usuario. Al optimizar estos factores, es más probable que un sitio web aparezca en los primeros resultados de búsqueda y traccionar más volumen de tráfico.", "El posicionamiento web también incluye la investigación y el uso de palabras clave relevantes para tu sector profesional. Incorporar estas keywords de manera estratégica en el contenido y en las etiquetas de tu site ayuda a los motores de búsqueda a comprender mejor la temática de tu proyecto online y a clasificarlo para las búsquedas apropiadas.", 'Además, el posicionamiento web incluye la generación de enlaces de calidad desde otros sitios web hacia el suyo. Estos enlaces "externos" (Backlinks) funcionan como votos de confianza para los motores de búsqueda y pueden ayudar a mejorar el posicionamiento de su sitio.']
                },
                {
                  pregunta: "Desarrollamos estrategias SEO únicas y personalizadas",
                  respuesta:["¿Cansado de seguir las mismas pautas en SEO sin obtener los resultados deseados? Nuestra agencia SEO en Madrid ofrece estrategias personalizadas para adaptarse a las necesidades específicas y objetivos del negocio. Contáctanos hoy y descubre cómo podemos ayudarte a mejorar tu visibilidad y posicionamiento en los motores de búsqueda y aumentar el tráfico orgánico con un enfoque único y personalizado.", "Una estrategia SEO (Search Engine Optimization, u Optimización para Motores de Búsqueda en español) es un plan detallado de acciones que se llevan a cabo con el objetivo de mejorar la visibilidad de una página web o URL en los resultados de búsqueda orgánicos de los motores de búsqueda.", "Una estrategia SEO incluye diversas acciones, siendo las más comunes:","Investigar y seleccionar palabras clave relevantes para optimizar la página web.","Optimizar los etiquetados HTML de tu web para orientarlos a las búsquedas de los usuarios y mejorar su posicionamiento en las SERPs","Optimizar el contenido de la página web para que sea más atractivo para los motores de búsqueda.","Mejorar la estructura y la navegación de la página web para que sea más fácil de usar y de entender para los motores de búsqueda.","Analizar y optimizar el perfil de enlaces entrantes de la página web para mejorar su autoridad y confianza en los ojos de los motores de búsqueda.","El objetivo final de una estrategia SEO es conseguir que la página web aparezca en los primeros resultados de búsqueda para las palabras clave relevantes, lo que puede aumentar el tráfico hacia la página y, por lo tanto, aumentar las posibilidades de conversión y generación de ingresos.","Para desarrollar una estrategia SEO efectiva, es necesario tener un conocimiento profundo sobre cómo funcionan los motores de búsqueda y cómo se puede optimizar una página web para atraer más tráfico orgánico. También es importante estar al tanto de las últimas tendencias y actualizaciones en el mundo del SEO para poder aplicarlas de manera efectiva."]
                },
                {
                  pregunta: "¿Necesitas una agencia SEO en Madrid?",
                  respuesta:["Entendemos que el mundo digital es un lugar cambiante y siempre estamos al tanto de las últimas tendencias y tecnologías para asegurarnos de que nuestros clientes estén siempre un paso adelante. Además, nuestro equipo de profesionales se dedica a proporcionar un servicio excepcional y a establecer relaciones duraderas con nuestros clientes.", "Trabajamos para comprender tus objetivos y desarrollar una estrategia SEO personalizada que se adapte a tus necesidades y las de su empresa."]
                },
              ],
        };
    }

    throw error(404, 'Not found');
}